#!/bin/bash
filename=$1
filehead=${filename/%.c}
if [ "$2" ]; then
    bcfilehead=${2/%.bc}
else 
    bcfilehead=$filehead
fi
clang-13 -c -emit-llvm -O0 -g -gcolumn-info -Xclang -disable-O0-optnone -I/usr/local/share/smack/include -DMEMORY_MODULE_NO_REUSE_IMPLS -fcolor-diagnostics -o $bcfilehead.bc $1
llvm-dis $bcfilehead.bc
opt -mem2reg -S $bcfilehead.ll -o $bcfilehead-opt.ll
# echo $filehead