#!/bin/bash
# 使用clang生成llvm ir的脚本
# 主文件需要放在脚本参数的后面
# 返回文件名total-opt.ll
bcfile=${@//.c/.bc}
for file in $@
do
path=$(dirname $file)
clang-12 -c -emit-llvm -O0 -g -gcolumn-info -Xclang -disable-O0-optnone -I/usr/local/share/smack/include: -DMEMORY_MODULE_NO_REUSE_IMPLS -fcolor-diagnostics $file -o ${file//.c/.bc}
done
if [ $# -eq 1 ]; then
    mv $bcfile $path/total.bc
else
    llvm-link-12 $bcfile -o $path/total.bc
    rm $bcfile
fi
llvm-dis-12 $path/total.bc
opt-12 -mem2reg -S $path/total.ll -o $path/total-opt.ll
rm $path/total.ll
rm $path/total.bc
# echo $filehead