#!/bin/bash
# 使用clang生成llvm ir的脚本
# 主文件需要放在脚本参数的后面
# 因为path取的是最后一个文件的path， 实现这样一个功能，所以文件都在最后一个文件的路径里生成
# 返回以最后一个文件名为名的ir文件

clang_opt=""
while getopts ":c:" o; do
    case "${o}" in
        c)
			clang_opt=${OPTARG}
            ;;
        *)
           file=${file}+${OPTARG}
            ;;
    esac
done
shift $((OPTIND-1))


for file in $@
do
path=$(dirname $file)
done


totalfile=$path"/total.bc"

res=""
for file in $@
do
dirfile=$path"/"$(basename $file)
echo $dirfile
dirfile=${dirfile//.c/.bc}
echo $dirfile
res=$res" "$dirfile
clang-12 -c -emit-llvm -O0 -g -gcolumn-info -Xclang -disable-O0-optnone -DMEMORY_MODULE_NO_REUSE_IMPLS -fcolor-diagnostics -I/home/luwei/smack/share/smack/include $clang_opt $file -o $dirfile
done
if [ $# -eq 1 ]; then
    mv $dirfile $totalfile
else
    llvm-link-12 $res -o $totalfile
    rm $res
fi
llvm-dis-12 $totalfile
rm $totalfile
totalfile=$path"/total.ll"
opt-12 -mem2reg -S $totalfile -o $totalfile
mv $totalfile ${dirfile//.bc/.ll}
# echo $filehead